name: Test site build

on:
  pull_request:
    branches:
      - dev

jobs:
  test_build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true
      - name: Build
        run: chmod +x build-site.sh && ./build-site.sh
        env:
          SELENIUM_CI_TOKEN: ${{secrets.SELENIUM_CI_TOKEN}}
      - name: Build website
        run: cd site_source_files && hugo
